### PR TITLE
Added /multiplereplace:<list> to command line convert

### PR DESCRIPTION
**Pull request by xylographe**
Where \<list\> is a comma separated file name list
The name "." represents replace rules from Settings.xml

The `/multiplereplace` switch is equivalent to `/multiplereplace:.`

Also added `/overwrite` switch to the usage message (overlooked in previous PR).

### CODE REVIEW

**Comment by xylographe** [comment]
Improved command line convert error handling

- Moved error handling from MultipleReplace to CommandLineConvert
- Check existence of folders, validity of frame rates, etc.
- Do not start conversion if options are invalid

**Comment by xylographe** [comment]
@niksedk 
What are the acceptable minimum and maximum frame rates (`/targetfps`, `/fps`) ?

**Comment by niksedk** [comment]
@xylographe: I guess normal frame rates are between 23 and 30, but 1-120 occurs too...

**Comment by xylographe** [comment]
Ty, @niksedk 

I'm using `minimumFrameRate = 1.0` and `maximumFrameRate = 200.0`, hoping that these limits are not too restrictive, yet help guarding against silly typo's (e.g., `/targetfps:244` when I actually meant `/targetfps:24` :) ).

The most important TODO is check there are no unrecognised arguments (e.g., `ofset:…` i/o `offset:…`). I'll leave that for another PR. :)

**Pull request merged**
