### PR TITLE
Introduce StringBuilderPool

### PR DESCRIPTION
**Pull request by ivandrofly**
The new StringBuilderPool class has been added to provide an implementation of an object pool pattern specifically for StringBuilders. This object pool assists with the use and re-use of StringBuilders, where more-often used string builders are returned from the pool and the least used ones are dropped. Limitations on pool size and capacity of string builders are also set to manage resource usage.

### CODE REVIEW

**Comment by ivandrofly** [comment]
Add test specific for StringBuilderPool

**Comment by ivandrofly** [comment]
For some reason it look like appveyor is complaining about the **internal access modifier** in StringBuilderPool
which it was before (see the commit history above)!

Also [InternalVisibleTo("Test)] is still present in LibSE project.

The image below shows that all the test are passing
image

**Comment by niksedk** [comment]
I did a quick test... and it's a lot slower (probably better for the GC though).
I will have to do a bit more testing...

**Comment by ivandrofly** [comment]
Consider that this is not meant to be the replacement of the StringBuilder in the entire system.
There are specific cases where pool is used, for example loop => caller => callee {create new stringbuilder)!
If the loop is running ~5000 times that is creating 5K instance to GC to deal with it!
Injecting stringbuidler 2/n level above just to use it somewhere isn't that great I think.

Note that due to the thread-safe capability, that might impact the performance a bit but it's future proof!

**Comment by niksedk** [comment]
Definitively interesting... if we get some memory issue then let's look at it again. Until then, I prefer the performance.

**Pull request closed without merging**
