### PR TITLE
Show HEX and ASSA color with RGB and copy on click

### PR DESCRIPTION
**Pull request by OmrSi**
Thought they would make nice additions from my personal experience. :)

### CODE REVIEW

**Comment by niksedk** [comment]
Perhaps it's better with a context menu like?
````
  Copy to clipboard as RGB HEX "FFBB55"
  Copy to clipboard as ASSA HEX "BBFF55"
  Copy to clipboard as RGB "RGB(255,66,44)"
````

**Comment by OmrSi** [comment]
Hmm. Wouldn't the color change when you try to click on the menu item?
I don't see a point in copying RGB for subtitling purposes, and copying when clicking makes more sense, I think.
You know, since it saves the color when you click.

**Comment by OmrSi** [comment]
I agree that a right-click to copy ASSA color isn't the brightest idea, but it seems a good trick for a user to discover. xD

**Comment by OmrSi** [comment]
@niksedk You'll just have to update the `.resx` file yourself. I write the designer code manually because the sizes get all messed up when I changed something, so the `.resx` file isn't updated.

**Comment by niksedk** [comment]
Nice, thx :)

A bit related, I've some problems with colors in ASSA after burn-in. ASSA colors are changed a little. which is not good... I've compensated by using ` var colorMatrix =  "bt601:bt709";` in the image color picker, but I guess I will have to move this to the burn-in and change the color matrix for the burn-in assa file in SE. 
Any thoughts on this?

**Comment by OmrSi** [comment]
No, sorry, I haven't come across this before. :\

The only problem that comes to mind is that usually when I use external color pickers, I notice that they don't exactly match the color I take from the video for some reason, so I take the color and use a lighter version so it visually matches the video.
Now I'm thinking, would that color then match after I burn the subtitle in? Strange.

**Pull request merged**
