### PR TITLE
Add line width (in pixels) syntax validation, labels and statistics

### PR DESCRIPTION
**Pull request by Flitskikker**
This is for #4059.

It's now possible to toggle the actual widths in pixels next to the character counter.
As not all characters have the same width, the "maximum amount of characters per line" is not always reliable for checking if the subtitles don't exceed the safe area. Now you can safely check this using this feature.

image

image

(also works in translator mode)

Syntax coloring can be toggled from the settings:

image

Click the button to modify the actual calculation settings, and to toggle the new UI options.

image

By default, all options are turned off. The default calculation settings are based on Spot's safe area settings (used by professional Dutch subtitlers/broadcasters). ([Reference](https://user-images.githubusercontent.com/3516155/77255534-96c34680-6c68-11ea-853e-d100a8e38d1d.png): Arial 24pt, 720 px - 10% left and right safe area)

Also generates statistics when enabled:

image

Notes:
- I didn't add it to profiles, because I think it's quite niche and not really widely used across all languages. Can always be added later.
- Text widths are calculated using `TextRenderer.MeasureText`. It seems like `Graphics.DrawString`, as used by the plugin, is less accurate. `TextRenderer.MeasureText` is also not 100% accurate (it leaves some padding even when padding is disabled). I tried drawing the text to a Bitmap and then calculating the exact width (not using GetPixel but reading directly from memory using BitmapData), which gave more accurate results, but it was too slow. Now using `TextRenderer.MeasureText` in combination with a correction value, based on testing and comparing with Spot. Not ideal, but it works in most cases and is at least more accurate than the CheckLineWidth plugin.
- All settings and i18n added.

Please test it and let me know what you think!

### CODE REVIEW

**Comment by niksedk** [comment]
Looks good to me :)

Two/three minor issues:
1) TextWidth should dispose the `measureFont`.
2) No need for a setting regarding statistics - just always show it.
3) If the main win width is very small - perhaps the pixels lengths should be hidden?

**Comment by OmrSi** [comment]
Why always show it? If a person isn't interested in this, he wouldn't activate it and it wouldn't show up in statistics.
I'm saying, if the option to `color text if too wide` is activated, show it in statistics, if not, don't.
This is just my opinion. :D

**Comment by OmrSi** [comment]
I also think it should always show the width under the text box if `color text if too wide` is activated, or else you would get a colored line without an apparent reason:
image

Why is it red here? It's not clear.
@niksedk What do you think?

**Comment by Flitskikker** [comment]
@OmrSi @niksedk 
Thanks for your comments! I'll remove the two checkboxes and toggle those options based on whether "Color text if too wide" is enabled or not.

**Comment by Flitskikker** [comment]
@niksedk 
Issues fixed. Thanks for your feedback.

**Pull request merged**
