### PR TITLE
Implement IDisposable in translators and properly dispose HttpClient …

### PR DESCRIPTION
**Pull request by ivandrofly**
…instances

Several classes, particularly the ones related to translation services, have been modified to implement IDisposable interface. Additionally, all instances of HttpClient are being disposed properly now using "using" keyword. This will help ensure that system resources are promptly released when they're no longer required, potentially improving application performance and stability.

### CODE REVIEW

**Comment by niksedk** [comment]
Nice :)

**Comment by niksedk** [comment]
Hm, could this have caused the "Purfview faster whisper" model download to fail? There seems to be a problem...

**Comment by niksedk** [comment]
Message: DownloadAsync failed - https://huggingface.co/Systran/faster-whisper-tiny.en/resolve/main/config.json

System.InvalidOperationException
Message: This instance has already started one or more requests. Properties can only be modified before sending the first request.
StackTrace:    at System.Net.Http.HttpClient.CheckDisposedOrStarted()
   at System.Net.Http.HttpClient.set_Timeout(TimeSpan value)
   at Nikse.SubtitleEdit.Core.Http.HttpClientDownloader.<DownloadAsync>d__9.MoveNext() in C:\git\subtitleedit\src\libse\Http\HttpClientDownloader.cs:line 41

**Comment by ivandrofly** [comment]
Taking a look

**Comment by ivandrofly** [comment]
Is any progress done here https://github.com/SubtitleEdit/subtitleedit/commit/4a02923c8024210ec972a257e71be6e1c0d845e3

**Comment by ivandrofly** [comment]
> Message: This instance has already started one or more requests. Properties can only be modified before sending the first request.

Seems like it's not possible to change HttpClient it's time out once you start using it. An easy fix would have been setting the time-out property at the constructor instead of `HttpClientDownloader.DownloadAsync` method which is invoked several on the same instance.

**Pull request merged**
