### PR TITLE
Work on live spell check

### PR DESCRIPTION
**Pull request by OmrSi**
How it looks:
image

TODO:
1. ~~Add an option to add the word to the dictionary.~~
2. ~~Add an option to activate in the UI.~~
3. ~~More work on isolating the words.~~
4. ~~Make loading dictionaries async.~~

@niksedk Please check it out and let me know what you think.

Closes https://github.com/SubtitleEdit/subtitleedit/issues/4347 when it's done. :)

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk Do refactor the code :)

**Comment by OmrSi** [comment]
Loading dictionaries asynchronously stops the timer for a bit while they are being loaded, I don't know if this is good or if a new timer should be added.

**Comment by niksedk** [comment]
Very close :)

1) The live spell check should not spell check the word being typed (like word).

2) I opened a Danish subtitle, and the live spell check looked very much like English.

**Comment by OmrSi** [comment]
About 1: How can you tell the word is done? You detect a space or a new line, but what if the user changed a work that already exists?

About 2: it uses `LanguageAutoDetect.AutoDetectLanguageName("", subtitle)` to detect that language, is google's better?

**Comment by OmrSi** [comment]
@niksedk Okay, number 2 was a bigger challenge than I thought.
It's not enough to detect the language, you have to check if the dictionary files for it are available.
I think I got it working.
It should let the user download the dictionary if it's not downloaded.

I'm still not clear on how number 1 can be achieved.

**Comment by OmrSi** [comment]
@niksedk Okay, I think this is the best I can do.
New words that are added to the end of the line will only be checked if certain keys were pressed, but old words will be checked while being written.

To be honest, I don't think I have anything more to add to this.

**Comment by niksedk** [comment]
@OmrSi: Happy new year :)
Will give it a test run later today.

**Pull request merged**
