### PR TITLE
SonicScenaristBitmap] - Remove unused loop/variable.

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by niksedk** [comment]
Please do not mix fix and refact...

**Comment by ivandrofly** [comment]
> Please do not mix fix and refact...

This one only contains refact

**Comment by ivandrofly** [comment]
Ups, sorry for unintentional close!!!

This one only contains refacts, fell free to close/merge :)

**Comment by ivandrofly** [comment]
@niksedk

Updated.

**Pull request merged**
