### PR TITLE
fix-common-error: fix set user default fix not working

### PR DESCRIPTION
**Pull request by ivandrofly**
image

### CODE REVIEW

**Comment by niksedk** [comment]
What exactly is not working?

**Comment by ivandrofly** [comment]
> What exactly is not working?

When you check the checkboxes from listview which fixes you want to be the default, they are supposed to be set as default... but that is not working!

Let say you only want **Fix commas** and **Remove >>** to be your new personal default instead of Subtitle-Edit's default - when you click the context-menu **Set current fixes as default** it will always reset to:

```c#
EmptyLinesTicked = true;
            OverlappingDisplayTimeTicked = true;
            TooShortDisplayTimeTicked = true;
            TooLongDisplayTimeTicked = true;
            TooShortGapTicked = false;
            InvalidItalicTagsTicked = true;
            BreakLongLinesTicked = true;
            MergeShortLinesTicked = true;
            UnneededPeriodsTicked = true;
            FixCommasTicked = true;
            UnneededSpacesTicked = true;
            MissingSpacesTicked = true;
            UppercaseIInsideLowercaseWordTicked = true;
            DoubleApostropheToQuoteTicked = true;
            AddPeriodAfterParagraphTicked = false;
            StartWithUppercaseLetterAfterParagraphTicked = true;
            StartWithUppercaseLetterAfterPeriodInsideParagraphTicked = false;
            StartWithUppercaseLetterAfterColonTicked = false;
            AloneLowercaseIToUppercaseIEnglishTicked = false;
            TurkishAnsiTicked = false;
            DanishLetterITicked = false;
            FixDoubleDashTicked = true;
            FixDoubleGreaterThanTicked = true;
            FixEllipsesStartTicked = true;
            FixMissingOpenBracketTicked = true;
            FixMusicNotationTicked = true;
            FixContinuationStyleTicked = false;
            FixUnnecessaryLeadingDotsTicked = true;
            NormalizeStringsTicked = false;
```

**Comment by niksedk** [comment]
Hm, it works fine here... a video or some screenshots?

**Comment by ivandrofly** [comment]
This can be closed, the expected was when you click the context menu it will check the item and save it (and the pre-checkeds) as defaults...

**Pull request closed without merging**
