### PR TITLE
Translate a new line added.

### PR DESCRIPTION
**Pull request by abdollahim**
Translate the <HelpFile> tag added.

### CODE REVIEW

**Comment by abdollahim** [comment]
Please check the problem to merge. Thanks

**Comment by niksedk** [comment]
Hi @abdollahim 

You can use XmlContentTranslator to update missing tags: https://www.nikse.dk/xmlcontenttranslator

image

**Comment by niksedk** [comment]
The `Version` tag should not be translated... 

(It's meant for an url, but I should probably just remove it)

**Comment by abdollahim** [comment]
Actually, I didn't change the version and just edit this line <HelpFile>فایل کمک رسانی</HelpFile>
Now, I see some other untranslated lines in your image, but in my XmlContentTranslator program, I didn't see anything.

**Comment by niksedk** [comment]
Ah, sorry. I meant the `HelpFile` tag should not be translated.

Yes, I think SE needs the XmlContentTranslator 1.11 now: https://github.com/SubtitleEdit/XmlContentTranslator/releases/download/1.11/XmlContentTranslator.zip

**Pull request closed without merging**
