### PR TITLE
FixEllipsesStartHelper BugFIx

### PR DESCRIPTION
**Pull request by ivandrofly**
CAIRNCROSS:Midnight... Issue

### CODE REVIEW

**Comment by ivandrofly** [comment]
@niksedk

**Comment by niksedk** [comment]
There was an error in FixEllipsesStart regarding a missing space, thx, but I don't think that "CAIRNCROSS:Midnight..." has anything to do with "FixEllipsesStart" - this missing space should be fixed in "Fix missing spaces" I think.

**Comment by ivandrofly** [comment]
yeah actually this problem is
pre += text.Substring(0, index + 1)
text = text.Remove(0, index + 1).TrimStart();

**Comment by niksedk** [comment]
Yes, this should be fixed now, right?
If not, what text will trigger this error?

**Comment by ivandrofly** [comment]
:+1: Now I see its fixed [here](https://github.com/SubtitleEdit/subtitleedit/commit/6b9fd3c1f8fe2262223d607049a2df89384b6581#diff-2093bdcb87d2e9a970d7eaa40f5a04d5R104) in fact I didn't rebase my branch with SE\master

**Pull request closed without merging**
