### PR TITLE
Yet another try to fix Arabic comma in RichTextBox

### PR DESCRIPTION
**Pull request by OmrSi**
It was adding a Unicode char for each comma in the line.

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk Something strange is happening and I don't know why.
Sometimes the input language changes on its own when I type a space in the richtextbox:
Untitled Project

**Comment by niksedk** [comment]
> 
> 
> @niksedk Something strange is happening and I don't know why.
> Sometimes the input language changes on its own when I type a space or a dot or a new line in the richtextbox:
> Untitled Project
> 
> Notice how the language gets changed each time I enter a space.
> it happens when I:
> 
>     1. Open SE with the language set to English.
> 
>     2. Add a line and write an English letter.
> 
>     3. Delete that letter and switch the language.
> 
>     4. Write a word and press space.
> 
> 
> I think it has something to do with the temp richtextbox's rtf.

I cannot re-create this with Danish... you can try to remove the temp and just use the existing rtf...

**Comment by OmrSi** [comment]
@niksedk It works after removing the temp, but the issue it the updates to the text are visible to the user, like when it selects the whole text to set the color, the user can see the highlight.

**Comment by niksedk** [comment]
> 
> 
> @niksedk It works after removing the temp, but the issue it the updates to the text are visible to the user, like when it selects the whole text to set the color, the user can see the highlight.

does SuspendLayout/ResumeLayout help?

**Comment by OmrSi** [comment]
No, it doesn't seem to help:
Untitled Project

I tried to make it only highlight again when the tags are changed, but that causes an issue at the beginning and end of lines.

**Comment by niksedk** [comment]
Perhaps with this: https://stackoverflow.com/questions/3282384/richtextbox-syntax-highlighting-in-real-time-disabling-the-repaint

**Comment by OmrSi** [comment]
Yes, it works very well.

**Pull request closed without merging**
