### PR TITLE
Refact in StartNumberingFrom

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by XhmikosR** [comment]
It's not fixed; the `?w=1` is one of the GitHub "cheats". You can see more [here](https://github.com/tiimgreen/github-cheat-sheet).

**Comment by ivandrofly** [comment]
Ah okay I think I'm going to close this one and re-pull ;)

**Comment by XhmikosR** [comment]
You better read about git more. It's not so hard :p

**Comment by ivandrofly** [comment]
yeah I see :smile:

**Pull request closed without merging**
