### PR TITLE
Add chapters support

### PR DESCRIPTION
**Pull request by OmrSi**
Closes: https://github.com/SubtitleEdit/subtitleedit/issues/3267

Added a menu item to show chapters for Matroska files on video and waveform.
Added shortcuts to move between chapters.

Some changes are just switching to auto property, I'm sorry if I should have done it in a separate commit.

Please let me know if you'd like me to make any changes.

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk Do you think it would be better to have the option as an item in the Video menu instead of a hidden option?

**Comment by OmrSi** [comment]
I'm thinking of making this an item in the video menu instead of a hidden option.

**Comment by OmrSi** [comment]
Okay, now it's shown in the video menu if the file is MKV, and shows a message if there are no chapters in the file.
I think it's better this way.

**Comment by niksedk** [comment]
Ups... wrong branch, sorry ;)

**Comment by OmrSi** [comment]
And to think all of this can be done with just `mediaPlayer.chapters = Task.Run(() => matroska.GetChapters());` in .NET 4.5. ^^"

**Comment by niksedk** [comment]
Just give it a quick run... could you add the chapter text too?
 (we can also add that later)

**Comment by niksedk** [comment]
Yes, after 4.5+ some code could be improved :)

**Comment by OmrSi** [comment]
Yes, I can parse the chapters text, put where should it show up?

**Comment by niksedk** [comment]
The text could show up in the waveform.

**Comment by OmrSi** [comment]
Do you think it would be better as tuples or class?

Also, where on the waveform? I imagine it would cause an issue if it's overlapping with the subtitle text.
Wo you think it should show up on the right side in the middle of the chapter line?

**Comment by niksedk** [comment]
I would prefer classes... very easy to make :)

**Comment by OmrSi** [comment]
This was my first experience with tooltips, so please do check out the code. :D

**Comment by OmrSi** [comment]
@niksedk I've noticed that the tooltip is flickering, I couldn't find a way to fix it.

**Comment by niksedk** [comment]
Not really sure what you mean about tooltip? Screenshot?

Looks good :)
Perhaps you can use a background like bookmarks, as chapter text is a bit hard to read:
image
And perhaps another color than white for text/vertical line? Yellow or ?

**Comment by OmrSi** [comment]
A tooltip shows up on video with the chapter's name :D
image

**Comment by OmrSi** [comment]
I'm not very good with colors, so please do change it if it's not good.

**Comment by niksedk** [comment]
The color looks fine to me ;)
Could you put the color in settings? 
And perhaps use it in the video player progress bar too?

**Comment by OmrSi** [comment]
Should the user be able able to choose it from the UI or just in the settings file?

**Comment by niksedk** [comment]
Settings is fine :)
Yeah, you're right. Don't look clear enough.

**Comment by OmrSi** [comment]
Do you think red looks better for an initial color instead of purple?
image

And on a related note, should the color on the video take the color from the settings as well?

**Pull request merged**
