### PR TITLE
Remove style page from the settings and add categories to Assa

### PR DESCRIPTION
**Pull request by OmrSi**
@niksedk There have to be together, adding categories and removing the style page makes the default Ass styles be taken from the storage's default category, which means the `SubtitleSettings` Ass options are no longer needed because they can't be set from any place.

Closes https://github.com/SubtitleEdit/subtitleedit/issues/4702, Closes https://github.com/SubtitleEdit/subtitleedit/issues/4483

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk Can you check this before adding more ASSA changes? It's causing conflicts each time.

**Comment by niksedk** [comment]
This is for after 3.6.0, right?

**Comment by OmrSi** [comment]
It was supposed to be, but I see you're still adding some things for ASSA.

It's up to you, but it's ready.
If you leave it to 3.6.0, tell me when you want to review it so I can resolve any conflicts that will show up in the future.

**Comment by niksedk** [comment]
I guess it for after 3.6.0 due to language tags... alternately you could "borrow" if other windows have the same texts...

I'm not adding things for ASSA - at least not visible things. I've been fixing a few bugs though.

**Comment by OmrSi** [comment]
I guess so.
I couldn't find "Categories" in other places, it's called "Groups" for Multiple Replace.
Also, I think the note is a big dealbreaker.
I'm sure `Note: "Default" styles will be applied to new ASSA files` isn't available anywhere else.

**Pull request merged**
