### PR TITLE
Update zh-Hans.xml

### PR DESCRIPTION
**Pull request by nkh0472**
For https://github.com/SubtitleEdit/subtitleedit/commit/24ce68dece0f35066c75909d3505fd7bc9ed035f

---
I`m not sure why Line 8 was modified in commit 569bcc2f6d44f966cfbf53dd42d7efb18454def4.
No matter this item is useless or something, it is still shown in XML Content Translator. And after translating, it turns back to before.

### CODE REVIEW

**Comment by niksedk** [comment]
About line 8, is not a tag to be translated but rather an url pointing to a translated help page, like https://github.com/SubtitleEdit/subtitleedit/blob/master/src/ui/Languages/es-ES.xml#L8

**Comment by nkh0472** [comment]
Since there doesn`t have a Chinese version of the helpfile, I replaced it with the English version.

**Comment by niksedk** [comment]
> Since there doesn`t have a Chinese version of the helpfile, I replaced it with the English version.

That will work fine, could you just leave it empty? When empty the default English link will also be used.

**Comment by nkh0472** [comment]
> > Since there doesn`t have a Chinese version of the helpfile, I replaced it with the English version.
> 
> That will work fine, could you just leave it empty? When empty the default English link will also be used.

That`s OK... But the Translator will always show it as untranslated, looks quite annoying.

**Comment by LeonCheung** [comment]
@nkh0472 Hi, could you help to check if the #5675 issue occurs to you? Thanks!

**Pull request merged**
