### PR TITLE
[OcrFixEngine] - Optimize fixing ocr-hardocded.

### PR DESCRIPTION
**Pull request by ivandrofly**
Optimization for **OCR fix engine**:
Before: ~4n
After: n

Merry christmas @niksedk  | @diomed  | @xylographe 🎄

### CODE REVIEW

**Comment by diomed** [comment]
Merry Christmas @ivandrofly  & you all! 
Have a happy holidays 🎄 🎅 🎁

**Comment by aaaxx** [comment]
Shouldn't these match the ones in [subtitleedit/libse/Dictionaries/OcrFixReplaceList.cs](https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Dictionaries/OcrFixReplaceList.cs#L282)?

**Comment by niksedk** [comment]
Merry Christmas :)

**Comment by ivandrofly** [comment]
> Shouldn't these match the ones in subtitleedit/libse/Dictionaries/OcrFixReplaceList.cs?

That is probably true, but I think they shouldn't be merged 'cause it looks like they doesn't share same context.

**Pull request merged**
