### PR TITLE
Add "Toggle subtitle visibility" shortcut

### PR DESCRIPTION
**Pull request by OmrSi**
Closes https://github.com/SubtitleEdit/subtitleedit/issues/3226

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk Would you like me to change the name to "Toggle subtitle preview" or something?

**Comment by niksedk** [comment]
Hm, what about "Toggle on-video-preview"... (mpv handles preview text)

**Comment by OmrSi** [comment]
I'm with you on that.
I actually wanted it to work just with MPV, but I thought you'd want it to include all.

**Comment by OmrSi** [comment]
How is it now?

**Comment by OmrSi** [comment]
I guess the name was too vague...

**Comment by niksedk** [comment]
I was thinking about a toggle for this:
image

(vlc might potentially get the same in the future - if it ever catches up to mpv api :)

**Comment by OmrSi** [comment]
Hmm, I think it makes more sense this way.
I mean, you're not changing the preview type altogether, you're just hiding the subtitle for a little while just to see what's behind it or for whatever reason, and you're not losing anything since the textbox is already in front of you.
It makes a lot of sense when you're put in this situation.
Also, you never know why a user would want to turn the preview on or off.

It can also be applied to VLC when it gets implemented.

**Pull request closed without merging**
