### PR TITLE
:octocat: new additions and fixes

### PR DESCRIPTION
**Pull request by diomed**
please don't touch asterisk on few places i put it back. thank you.

### CODE REVIEW

**Comment by xylographe** [comment]
@diomed
```
<RegEx find="([dD])(eli)\b(m|š|mo|te|li|le|la|ti)" replaceWith="$1ijel$3" />
<RegEx find="([dD])(jeli)\b(m|š|mo|te|li|le|la|ti)" replaceWith="$1ijel$3" />
<RegEx find="([oO])(zlijed)\b(a|e|i|u|om|ama)" replaceWith="$1zljed$3" />
<RegEx find="([pP])(oseti)\b(o|m|š|la|li|le|lo|ti)?" replaceWith="$1osjeti$3" />
<RegEx find="([pP])(revoz)\b(a|u|om|ovi|ovima)?" replaceWith="$1rijevoz$3" />
<RegEx find="([sS])(eti)\b(t|o|m|š|la|li|le|ti)" replaceWith="$1jeti$3" />
<RegEx find="([sS])(ljed)\b(a|e|i|u|om|im|iš|imo|ite|e|ili)" replaceWith="$1lijed$3" />
```
`\b`: [The match must occur on a boundary between a \w (alphanumeric) and a \W (nonalphanumeric) character.](https://msdn.microsoft.com/en-us/library/az24scfc%28v=vs.110%29.aspx)
```
<RegEx find="[0-9](-ogodišnj)(i|a|e|u)" replaceWith="$1-godišnj$3" />
 ==> <RegEx find="([0-9])(-ogodišnj)(i|a|e|u)" replaceWith="$1-godišnj$3" />
```
```
<RegEx find="(A|a)(las)(ka|ku|ki|ci)" replaceWith="Aljas$2" />
 ==> <RegEx find="(A|a)(las)(ka|ku|ki|ci)" replaceWith="Aljas$3" />
 or  <RegEx find="(A|a)(las)(ka|ku|ki|ci)" replaceWith="$1ljas$3" />
```
And, perhaps:
```
<RegEx find="[A-Z][a-z](eyj)[a-z]" replaceWith="ey" />
 ==> <RegEx find="(\p{Lu}\p{Ll})(eyj)(\p{Ll})" replaceWith="$1ey$3" />
```

**Comment by diomed** [comment]
Thank you, once again, hawk eye @xylographe :smiley: 

What is powershell? Where is that?

**Comment by xylographe** [comment]
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`, or
`C:\Windows\System\WindowsPowerShell\v1.0\powershell.exe`.
\- `[regex]` is a shortcut for `[System.Text.RegularExpressions.Regex]`.
\- `[regex]::Replace()` is like `[regex]::IsMatch()` with the replacement as third argument.

The `\b` at the end is necessary, either
 `([sS])(eti)(|t|o|m|š|la|li|le|ti)\b`, or
 `([sS])(eti)(t|o|m|š|la|li|le|ti)?\b`.
Of course, `([sS])` can also be written `(s|S)`, if you prefer.

The `\b` at the start depends on what you want to match. For example. `\b(s|S)(eti)(|t|o)\b` matches whole words "**seti**", "**setit**", "**setio**", "**Seti**", "**Setit**", and "**Setio**". Without the first `\b` it will also match at the end of a word, e.g. "en**setio**".
If combined words in Croation are concatenated like in German ("Datei" + "System" ==> "Dateisystem"), you probably don't want that boundary at the start.

**Comment by diomed** [comment]
yes, I've noticed that if I don't add \b in beginning and end of the words it automatically changes ones it shouldn't. I'll have to fix that in a few more words.
Apparently this branch failed checks. Is there something wrong with it,  like some kind of syntax error ?

**Comment by xylographe** [comment]
The failure is some (time out) issue with AppVeyor  Ignore it.

**Pull request merged**
