### PR TITLE
Fixes for #3112

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by ivandrofly** [comment]
> don't work, not detect long line

What do you mean?

**Comment by marb99** [comment]
look to image above. "nothing to fix but a few...."

is a long line but don´t fix anything

**Comment by ivandrofly** [comment]
> look to image above. "nothing to fix but a few...."
> is a long line but don´t fix anything
> I downloaded subtitleedit-master made the changes like your fix and tested the result is don´t fix anything, does not even detect that a long line

That is the purpose, a paragraph that is a dialog (as the one above) shouldn't be changed...

**Comment by marb99** [comment]
> 
> 
> > look to image above. "nothing to fix but a few...."
> > is a long line but don´t fix anything
> > I downloaded subtitleedit-master made the changes like your fix and tested the result is don´t fix anything, does not even detect that a long line
> 
> That is the purpose, a paragraph that is a dialog (as the one above) shouldn't be changed...

Ohhh, oki, but this wrong in my opinion, the second paragraph is a long line cause trouble on display eats letters because its a long line.

**Pull request closed without merging**
