### PR TITLE
[ExportText] - Fix/Update.

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by niksedk** [comment]
Looks good :)
Could you rename "CheckBoxAddNewLine2" to "AddNewLine2" or "AddNewAfterText2" or something else without the "checkbox"?

**Comment by ivandrofly** [comment]
Updated @niksedk

**Comment by niksedk** [comment]
The "AddNewAfterText2" does not quite work as expected - should add an extra blank line.

**Comment by ivandrofly** [comment]
@niksedk 👍 ?

**Pull request merged**
