### PR TITLE
Several code improvements

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by niksedk** [comment]
Nice comments! AI?
Some commits are nice, some I do not want... could you make each commit in a PR or should I just cherry pick?

**Comment by ivandrofly** [comment]
> Nice comments! AI? Some commits are nice, some I do not want... could you make each commit in a PR or should I just cherry pick?

Alright, I will try to send them individually!

> Nice comments! AI?

Yes, powerful stuff :)

**Comment by niksedk** [comment]
I think it's a lot easier for me with separate PRs... it is much harder to keep the big picture with these large mixed PRs. 

1+2 looks fine... 5+8 also. 9 is also fine.

10 requires a lot of testing + SE always uses brackets for nested statements like "if-statements".

**Comment by ivandrofly** [comment]
Alright, I will drop 10 for now and make sure it's on it' own PR

**Comment by ivandrofly** [comment]
#7133 
#7133 
#7133

**Comment by niksedk** [comment]
Thx <3

**Pull request closed without merging**
