### PR TITLE
Also show progress in taskbar.

### PR DESCRIPTION
**Pull request by FroggieFrog**
First commit with support for showing the progress in taskbar. (VobSubOcr)
I can't test other formats because I don't have them. (e.g. DvdSubRip)

### CODE REVIEW

**Comment by niksedk** [comment]
I think it possible to do without included dll files...

**Comment by FroggieFrog** [comment]
Why reinvent the wheel, when there is a official library from Microsoft?
It would end up in a bunch of PInvokes. Is this really better/preferable?

**Comment by niksedk** [comment]
I think it's included in .net 4...

**Comment by FroggieFrog** [comment]
Yes, but only in WPF. The app is Winforms...
http://msdn.microsoft.com/en-us/library/system.windows.shell.taskbariteminfo%28v=vs.100%29.aspx

**Comment by niksedk** [comment]
Perhaps I'm old-fashioned but I don't like bloat and extra dlls - I would *much* rather have only the needed functionality.
Minimal code: https://psycodedeveloper.wordpress.com/2013/01/29/displaying-progress-in-the-windows-7-taskbar/

**Pull request closed without merging**
