### PR TITLE
Fix for modify selection last column size

### PR DESCRIPTION
**Pull request by OmrSi**
It used to leave a white part.

### CODE REVIEW

**Comment by niksedk** [comment]
Did you test this with and without styles? (e.g. srt and ass)

**Comment by OmrSi** [comment]
@niksedk Yes. It seems to be working well here.

With srt:
image

With ass:
image

**Comment by OmrSi** [comment]
@niksedk Also, can I make a method in `UiUtil` to this operation `listViewFixes.Columns[listViewFixes.Columns.Count - 1].Width = -2;` instead of haveing to write it all each time?

Something like: 
```
internal void SetListViewLastColumnSize(this ListView listview)
{
    listview.Columns[listview.Columns.Count - 1].Width = -2;
}
```

**Comment by niksedk** [comment]
Had to revert as the horizontal scroll bar kept appearing.

**Comment by OmrSi** [comment]
@niksedk I guess I will have to take another approach.

**Pull request merged**
