### PR TITLE
Feature/use rich text box

### PR DESCRIPTION
**Pull request by niksedk**
Use RichTextBox control for subtitle text box which enables syntax coloring like this:

image

Should also make live spell check possible in the future.

Syntax coloring can be turned off (which will make SE use a normal TextBox control):
image

### CODE REVIEW

**Comment by OmrSi** [comment]
Opening SE with the normal TextBox causes it to not use the selected font, but default to another font:
image

My font:
image

**Comment by OmrSi** [comment]
Now the font isn't right when using syntax coloring:
image

**Comment by niksedk** [comment]
Thx :)
Hopefully font is working now!

**Comment by OmrSi** [comment]
Changing the text box type makes the text box active even without any lines:
image

**Pull request merged**
