### PR TITLE
[fixmissingspaces] - fixes #2390

### LINKED ISSUE #2390: Combinations "?-", ".-" and "!-" are not detected when checking for missing spaces
These lines contain cases which are not detected when SE checks for missing spaces.

```
43
00:08:41,083 --> 00:08:45,713
Etkö muista, teitkö murhan?-En.
44
00:08:49,258 --> 00:08:53,429
Ei kai semmoista hevin unohda.-Ei.
```

### PR DESCRIPTION
**Pull request by ivandrofly**
TODO: 

- [x] Add/Improve unit-tests regarding to **fix missing spaces**
- [ ] ready

if you could review this patch I got another one coming for fix-missing-spaces (didn't want to include it here) /cc @niksedk

### CODE REVIEW

**Comment by niksedk** [comment]
Why did you remove the question mark + exclamation mark checks for text like `Long made a plea deal?Did you know?` ?
Perhaps just add a dash/m-dash to the existing regex?

Also, the test methods should be named better...

**Comment by ivandrofly** [comment]
> Perhaps just add a dash/m-dash to the existing regex?

doing so won't fix text with html tags... I have rebase and updated the pr.

**Comment by niksedk** [comment]
Did you fix it for html tags, like `Etkö muista, teitkö murhan?<i>-En.</i>` ?

**Comment by ivandrofly** [comment]
> Did you fix it for html tags, like Etkö muista, teitkö murhan?<i>-En.</i> ?

yeah, it's handled.

ps: still working on this patch.

**Comment by niksedk** [comment]
If this is still relevant please add a new pr with info about why, what and unit tests

**Pull request closed without merging**
