### PR TITLE
Reset frame color

### PR DESCRIPTION
**Pull request by OmrSi**

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk The only bug left I can see, other than this one, is the select all click:
Untitled Project

**Comment by OmrSi** [comment]
This is still missing setting the color after opening a file.

**Comment by niksedk** [comment]
> 
> 
> @niksedk The only bug left I can see, other than this one, is the select all click:
> Untitled Project

Seems to be a feature... Wordpad also does this, but I can probably hack something...

**Comment by OmrSi** [comment]
> Seems to be a feature... Wordpad also does this, but I can probably hack something...

The issue with it is if you want to move the cursor to the beginning of the line.

I was saying this PR is missing setting the frame color when opening a subtitle:
image

I was looking where to set it but couldn't find the code that always gets executed when opening a file...

**Comment by niksedk** [comment]
Hacked the center select thing here: https://github.com/SubtitleEdit/subtitleedit/commit/4aeaa398390738d9362e898319f13cc4565da546

>I was saying this PR is missing setting the frame color when opening a subtitle:

I'm not really sure what you mean - looks fine to me...

**Comment by niksedk** [comment]
This here has been bugging me for a long time: https://github.com/SubtitleEdit/subtitleedit/commit/fca88ffbdef368322c72f9738a09c222d3822e1f

**Comment by OmrSi** [comment]
Nice hack. :D

> I'm not really sure what you mean - looks fine to me...

It should be Windowframe:
image

**Comment by OmrSi** [comment]
> This here had been bugging me for a long time: [fca88ff](https://github.com/SubtitleEdit/subtitleedit/commit/fca88ffbdef368322c72f9738a09c222d3822e1f)

Didn't notice that. I have the splitters values memorized, 446, 932, 300, and I always set them from the settings file when the size gets messed up. hehehe

**Pull request merged**
