### PR TITLE
Add setting for split behavior

### PR DESCRIPTION
**Pull request by Flitskikker**
Related to commit 0c657ae245c947b20f06cd9237f6e70d468e88b4 and #4026:
Make split behavior configurable (from which subtitle the gap will be substracted). For me it's more logical to set the gap to the left of the split point (Spot also does this).

image

Setting & i18n added.

### CODE REVIEW

**Comment by OmrSi** [comment]
@Flitskikker Don't you think it should go to the second line when it's: "add gap to the left"?

**Comment by Flitskikker** [comment]
@OmrSi I'm not quite sure what you mean. Could you please explain?

The idea is, when it's set to "Add gap to the left of split point":

I set the split point at the position where I want the second line to start (which is a few frames before the start of speech):

image

It then sets the start time of line 2 to the split point, and adds the gap at the left side of the split point, deducting time from line 1:

image

**Comment by OmrSi** [comment]
I mean, since you split it where the second starts, should the selection now be on the second?
I working on Netflix's platform and this is what happens, when you split it leaves the gap to the left and moves to the second line. (The selection moves to the second line)
In your picture, line 100 would be selected.

Also, what do you get from the Spectrograms?

**Comment by Flitskikker** [comment]
@OmrSi 
Ah, I understand. Yes, good idea actually! I'll see if I can change it tomorrow.
Do you think it should selected the left subtitle when it's set at "Add gap to the right of the split point"?

I find the spectograms really useful to distinguish speech, especially when there's a lot of background noise:

image

**Comment by OmrSi** [comment]
Yes, it already does that.
Because when it's to the right, you'd be setting the end of the first line.
While when it's on the left, you'd be setting the beginning of the second line.

Nice, I didn't know it can be used for that.

**Comment by OmrSi** [comment]
@Flitskikker You just need to add go to next to the condition of `SplitBehavior == 0` right?

**Comment by Flitskikker** [comment]
@OmrSi 
Yes. Had some GitHub issues yesterday.
Just pushed the fix: #4082

**Pull request merged**
