### PR TITLE
Update de-DE translation

### PR DESCRIPTION
**Pull request by xylographe**
add Settings.**AdjustSetEndTimeAndGoToNext** tag (3.4.5)
add Settings.**WaveformTextFontSize** tag (3.4.6)

### CODE REVIEW

**Comment by xylographe** [comment]
Why did AppVeyor fail on this PR???

**Comment by niksedk** [comment]
Perhaps some appVeyor bug? Just says "Not found".

**Comment by xylographe** [comment]
OK. As long as it didn't break anything…

Can I run these unit tests locally (in shell)? Or would I need AppVeyor?

**Comment by niksedk** [comment]
You can use VS Express if you don't have a full VS - I've not tried the "mstest" command tool but the UI runner is pretty easy to run...

**Comment by xylographe** [comment]
Thank you!

Via [mstest.exe](http://msdn.microsoft.com/en-us/library/ms182489.aspx) (which I couldn't find in VSE12.0), I found [vstest.console.exe](http://msdn.microsoft.com/en-us/library/jj155796.aspx). Works like a charm. :smile:

Only the __FixCommonOcrErrorsSlashIsL__ unit test fails.
`FixCommonErrorsTest.cs:497`: _// will fail if English dictionary is not found._
Strange, `~\AppData\Roaming\Subtitle Edit\Dictionaries` contains `en_US.dic` & `en_US.aff`.
Will investigate that later.

**Comment by niksedk** [comment]
Can you set it to run in x64 mode? The last unit test might pass in X64 mode...

**Comment by xylographe** [comment]
I tried `vstest.console Test.dll /platform:x64` (uses framework40) and `vstest.console Test.dll /platform:x64 /framework:framework45`. Same test still fails.

The error message is a bit strange:
```
Failed   FixCommonOcrErrorsSlashIsL
Error Message:
   Assert.AreEqual failed. Expected:<The font is ita/ic!>. Actual:<The font is italic!>.
Stack Trace:
   bij Test.FixCommonErrorsTest.FixCommonOcrErrorsSlashIsL() in c:\Users\Eric\Documents\Source\SubtitleEdit\src\Test\FixCommonErrorsTest.cs:regel 497
```
Shouldn't that be `Expected:<The font is italic!>. Actual:<The font is ita/ic!>.`

**Comment by xylographe** [comment]
*Almost* forgotten. :grin: 

For the record: test failure was caused by missing `vstest.console` argument `/settings:Local.testsettings`

**Pull request merged**
