### PR TITLE
Fix bug cursor won't wait for file to complete the download

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by ivandrofly** [comment]
I tested it /cc @niksedk

**Comment by niksedk** [comment]
I think the cursor is not handled well in error situations... in "wc_DownloadDataCompleted"...

**Comment by ivandrofly** [comment]
https://github.com/SubtitleEdit/subtitleedit/commit/a464adedab77f350a1c8430f56c6f1d83e7a3907 /cc @niksedk

**Comment by niksedk** [comment]
Ah, yes - did not see that... I thought of before 145 and before 156.

**Comment by ivandrofly** [comment]
:+1: ? /cc @niksedk

**Comment by niksedk** [comment]
Error handling not complete... I can also merge this and fix it?

**Comment by ivandrofly** [comment]
Go for it :)

**Comment by ivandrofly** [comment]
@niksedk  Do you have time to review this?

**Pull request closed without merging**
