### PR TITLE
Added Auto-Refresh user choise [Unready]

### PR DESCRIPTION
**Pull request by ivandrofly**
This is useful is you have a huge list of multiple-replace and you want to sort it without unload current subtitle...
PS:
- [x] - Add save to settings file
- [x] - Multi-langue support

### CODE REVIEW

**Comment by xylographe** [comment]
[Multi-langue support](https://github.com/xylographe/subtitleedit/commit/9a462718c80302fc8c5308d318667320cc31263c)
`git fetch "https://github.com/xylographe/subtitleedit" autorefresh`

**Comment by ivandrofly** [comment]
@xylographe :+1:

**Comment by xylographe** [comment]
Yes, on top of `ivandrofly:feature/feat-1`.

**Comment by xylographe** [comment]
[Add save to settings file](https://github.com/xylographe/subtitleedit/commit/a3133fe2d1d791c33563709a6a6898283e26c511)
`git fetch -np "https://github.com/xylographe/subtitleedit" autorefresh2`

This commit is on top of the previous branch, [_xylographe:autorefresh_](https://github.com/xylographe/subtitleedit/commit/9a462718c80302fc8c5308d318667320cc31263c)

**Comment by xylographe** [comment]
I was wondering, if, perhaps, it might be easier to test `checkBoxAutoRefresh.Checked` only in one location: inside `GeneratePreview()`. As in [this commit](https://github.com/xylographe/subtitleedit/commit/218f217317e36dbfed0723d16ce88fdaa1251727), for example.

**Comment by ivandrofly** [comment]
I tried git fetch nothing happened? @xylographe

**Comment by xylographe** [comment]
Try this, but beplace `<<local>>` with the branch name of `feature/feat-1` inside your local repository,

(1)  `git fetch -np "https://github.com/xylographe/subtitleedit" "autorefresh:autorefr1"`
(2)  `git fetch -np "https://github.com/xylographe/subtitleedit" "autorefresh2:autorefr2"`
(3)  `git rebase <<local>> autorefr1`
(4)  `git rebase autorefr1 autorefr2`
(5)  `git diff <<local>> autorefr1`
(6)  `git diff autorefr1 autorefr2`
(7)  `git push origin +autorefr2:feature/feat-1`

Steps (1)(2) create new branches in your local repository; (3)(4) will do nothing, unless you have re-based your original branch locally; (5)(6) for verification.

**Comment by xylographe** [comment]
Updated [Added Auto-Refresh Settings support](https://github.com/xylographe/subtitleedit/commit/2904dab98c516774f5ec49ad566ca21adcb24521)

**Comment by niksedk** [comment]
Could the preview generating be made to a 'cancel-able' background task or similar?
(should not display the wait cursor then)

**Pull request closed without merging**
