### PR TITLE
[GetDictionaries] - allow switching dictionary provider.

### PR DESCRIPTION
**Pull request by ivandrofly**
⚠️  Work in progress... ⚠️ 

TODO:

- [x] Fix long text in label Description
- [x] Fix download button
- [x] Localize
- [ ] Make all dictionaries available in embedded xml lookup file
- [ ] Ready ✔️ 

Hope this patch solves the dictionary hosting problem with: libreoffice.org and  sourceforge.net

### CODE REVIEW

**Comment by niksedk** [comment]
You're not really meant to be able to switch via UI (ppl don't know what is what and why...) but only as a last resort if the primary provider is down

**Comment by diomed** [comment]
@ivandrofly where can I find those dictionaries on github? can u gimme link?

**Comment by ivandrofly** [comment]
> @ivandrofly where can I find those dictionaries on github? can u gimme link?

https://github.com/einsiol/Dictionaries

**Comment by ivandrofly** [comment]
> You're not really meant to be able to switch via UI (ppl don't know what is what and why...) but only as a last resort if the primary provider is down

💯

**Comment by ivandrofly** [comment]
yeah by default libre-office will be selected, if anything goes wrong user-will be notified to switch provider....

**Comment by diomed** [comment]
sadly, not even libreoffice per my experience brings all correct words. people add their own words, 
but no one checks if they're really correct. some really aren't.. still, it's better than nothing.

**Pull request closed without merging**
