### PR TITLE
Add `Loop selected line` shortcut

### PR DESCRIPTION
**Pull request by OmrSi**
Somewhat related to https://github.com/SubtitleEdit/subtitleedit/issues/6137

I would understand if you think it doesn't look too good.

### CODE REVIEW

**Comment by niksedk** [comment]
@OmrSi : Could you make it work with "selected lines" (like F5 Play selection)?

**Comment by OmrSi** [comment]
@niksedk I really tried to make it work like that but I faced one problem that I could not solve.
Should I push a commit and you could take a look?

**Comment by niksedk** [comment]
Sure :)
What is the issue?

**Comment by OmrSi** [comment]
@niksedk This line:
image

I causing an issue, when looping it keeps skipping to the end of the first line.
So if you have 3 lines, it skips the first one and loops the other two.
I can't figure out what it's for or what condition I need to add here.

**Comment by niksedk** [comment]
Yes, there were some problems with `Play selection` when `Auto-continue` was on.
Also, going back to a previous video position is pretty slow which gives some problems - should probably have been async or have a callback for when setting video position is done.... perhaps at some later point...

So, I've updated Main.cs - which mean you might need to re-implement your main changes (and now you can use `_playSelectionIndexLoopStart` to set the paragraph start index for the first selected sub in the selection loop - I hope).

**Comment by OmrSi** [comment]
@niksedk This seems to be working as far as I can see. I removed the debugging lines left by your last commit.

The loop and selection play weren't being reset when pausing via a click on the video, I tried solving that by making a new event and resetting the fields, let me know if that behavior was intended so I can remove this change.

It's probably better if you can also do a couple of tests of your own.

**Comment by niksedk** [comment]
Only found a minor issue with `play selected lines` after `loop selected lines`. Those two command might not work on slow computers, but it works for me (except when using mpc-hc).

**Pull request merged**
