### PR TITLE
Try to fix current position flickering issue

### PR DESCRIPTION
**Pull request by OmrSi**
For https://github.com/SubtitleEdit/subtitleedit/issues/4987 

Should fix the flickring issue.

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk I don't know if it fixes the waveform hang issue, but it should.
His PC seems extra fast. :D

**Comment by OmrSi** [comment]
@niksedk I don't know if it fixes the waveform hang issue, but it should.
His PC seems extra fast. :D

**Comment by LucretiaAudrey** [comment]
Thanks a ton! It worked

**Comment by OmrSi** [comment]
@LucretiaAudrey Great. You got it!

**Pull request merged**
