### PR TITLE
'Stage' auto-generated language class

### PR DESCRIPTION
**Pull request by ivandrofly**
I don't know if you guys are getting this too but every time build I get this file change :confused:

### CODE REVIEW

**Comment by niksedk** [comment]
No I don't get that... but VS 2015 sometimes show way too many changes, like this: https://github.com/SubtitleEdit/subtitleedit/commit/66d1bd11907c80a7fabc3b03c3d321a3818bdec3

**Comment by niksedk** [comment]
Now I get "LanguageDeserializer" as changed...

**Comment by niksedk** [comment]
Is it better after this commit:https://github.com/SubtitleEdit/subtitleedit/commit/ffd7c6766c741529788886a1a6f6b501324de303 ?

**Comment by niksedk** [comment]
Do you use VS2015?
Are you sure your line endings are CRLF ?

**Comment by ivandrofly** [comment]
> Do you use VS2015?

Yean, I'm using VS2015.

> Are you sure your line endings are CRLF ?

Line ending was set to `Current Setting`

**Comment by ivandrofly** [comment]
> Is it better after this commit:ffd7c67 ?

Everything seems to wok fine :)

**Pull request merged**
