### PR TITLE
Update zh-Hans.xml

### PR DESCRIPTION
**Pull request by nkh0472**
For commits:
https://github.com/SubtitleEdit/subtitleedit/commit/21d814423abe315cb6760e79bb1e06f55bbf27da
https://github.com/SubtitleEdit/subtitleedit/commit/880d5dd1f042fb0e04bebd0b97a998878ad2eb7e

Actually, I do not fully understand what is the meaning of "Take time from" and "For Appropriate Line".

For the first one, is it meaning "extract/ generate" some "time codes"? Then, what is "from file name"? 
For the second one, is it meaning "auto select lines which needed to adjust"?

### CODE REVIEW

**Comment by niksedk** [comment]
"Take time from" is used in import. 
Import can import without time codes, or with auto generated time codes, or with time codes from current file.
Import with time codes from files name: some program can do ocr, and make a file for each line with a file name that contains time code.

"For Appropriate Line" is... that's a good question. I'll have to look into that...

**Comment by OmrSi** [comment]
> "For Appropriate Line" is... that's a good question. I'll have to look into that...

LOL
This was introduced in the PR https://github.com/SubtitleEdit/subtitleedit/pull/4959
It sets the Start/End time for the appropriate line based on the video position.
I could not find a better name for it.
There is a lengthy explanation of what it does in the PR.

**Comment by OmrSi** [comment]
> For the second one, is it meaning "auto select lines which needed to adjust"?

Basically, yes.

**Comment by nkh0472** [comment]
> This was introduced in the PR #4959
> It sets the Start/End time for the appropriate line based on the video position.
I could not find a better name for it.

A really cool feature! 
I guess call them "Auto adjust start time of adjacent line" and "Auto adjust end time of adjacent line" could be better?

**Comment by nkh0472** [comment]
If you don't want to change the name of them, then my PR is already translated correctly and ready to merge.

**Comment by OmrSi** [comment]
> > This was introduced in the PR #4959
> > It sets the Start/End time for the appropriate line based on the video position.
> > I could not find a better name for it.
> 
> A really cool feature!
> I guess call them "Auto adjust start time of adjacent line" and "Auto adjust end time of adjacent line" could be better?

They seem good to me.
I'll leave it up to Nikolaj to decide.

**Comment by OmrSi** [comment]
> > This was introduced in the PR #4959
> > It sets the Start/End time for the appropriate line based on the video position.
> > I could not find a better name for it.
> 
> A really cool feature!
> I guess call them "Auto adjust start time of adjacent line" and "Auto adjust end time of adjacent line" could be better?

They seem good, although they `auto` seems related to timing rather than choosing the line. 
`Set start/end for adjacent line` might be enough. 

I'll leave it up to Nik.

**Comment by niksedk** [comment]
I guess the help page could be improved with more info about shortcuts...

**Comment by OmrSi** [comment]
@niksedk There are also a lot of hardcoded shortcuts that should be exposed.
Like `Control + D` which selects the first lines of multiple selected lines in the list view or deselects the text in any textbox.
Also, `Control + Alt + Shift + F` that toggle frame mode on and off.
And others, the waveform shortcuts that set the start/end and other things.

**Pull request merged**
