### PR TITLE
Don't change default frame rate from source view

### PR DESCRIPTION
**Pull request by OmrSi**
If you select a frame rate then do some changes in source view, the default frame rate used to change.

### CODE REVIEW

**Comment by OmrSi** [comment]
How to replicate: 
1. Go to the source view. 
2. Add sone lines. 
3. Change the frame rate. 
4. Go back to list view. 
5. Create a new file. 

You will notice that the default frame rate changed.

**Comment by niksedk** [comment]
Hm, I think either the line should be removed, and we should update the UI combobox... perhaps just remove it?

**Comment by OmrSi** [comment]
Doesn't changing it in source view affect the subtitle? 
If it does, then shouldn't the "current frame rate" be changed?

**Comment by niksedk** [comment]
Yes, just deleting the line is probably the most simple solution - normally the frame rate should be ignored, but I guess when starting from blank, the frame rate could be useful... ?

**Comment by OmrSi** [comment]
Yes, I'm pasting a frame-based file and the frame rate should matter, I think.

**Pull request merged**
