### PR TITLE
Update Serbian OCRFixReplaceList

### PR DESCRIPTION
**Pull request by xylographe**
[1]
SE uses `CultureInfo.ThreeLetterISOLanguageName` as file name prefix :
```
PS> $c = [System.Globalization.CultureInfo]::CreateSpecificCulture('sr-RS')
PS> $c|fl NativeName, ThreeLetterISOLanguageName

NativeName                 : srpski (Srbija)
ThreeLetterISOLanguageName : srp
```

[2]
Fixed XML syntax
 \+ minor corrections/improvements.

### CODE REVIEW

**Comment by diomed** [comment]
btw. will it recognise ð as đ or not? 
if not we'll have to fix it.

also, if this is built in SE, maybe remove it?
  `
-    		+    
- 		+    `

**Comment by xylographe** [comment]
Ty, @diomed 
I'll change all `ð` inside a character class to `ðđ`.

**Comment by xylographe** [comment]
Updated.

**Comment by diomed** [comment]
actually, there is no need for ð.
either ð is letter đ -  or if it isn't, that symbol is completely non existent in this language.

**Comment by xylographe** [comment]
```
U+00F0 ð LATIN SMALL LETTER ETH
U+0111 đ LATIN SMALL LETTER D WITH STROKE
```
Removed all "LATIN SMALL LETTER ETH" from regular expressions.

**Pull request merged**
