### PR TITLE
[Settings] - Allow select custom path for vlc/mpc-hc.

### LINKED ISSUE #2010: MPC-HC interaction isn't working
screenshot
As you can see, MPC-HC is greyed out, but I have it installed properly on my system (`K-Lite_Codec_Pack_1090_Standard.exe`), it works without issues.
I'm running Win8.1 x64, both MPC-HC and SubtitleEdit are x64 as well.
Also, I'm curious on how exactly MPC-HC presence is resolved?

### PR DESCRIPTION
**Pull request by ivandrofly**
Fixes #2010 

If checkbox is not enabled, user can now double click and choose
a custom directory where mpc-hc.exe/vlc.exe is located.

### CODE REVIEW

**Comment by frozenspider** [comment]
This was done almost half a year ago, when can we expect it to be merged and released?

**Comment by niksedk** [comment]
If this is still relevant please add a new pr with info about why, what and unit tests

**Comment by Lokotito** [comment]
Sorry, but is this "double click" is enable for MPC-HC in last version (3.5.11) ?
I have some problems with VLC, but I didn't find a way to enable MPC-HC.
Note: I using zip files of SE and MPC-HC, in windows 10 64bits, so I never use their installation files.
¿Is there any way to use a custom path for MPC-HC?

Captura-SE

**Comment by xylographe** [comment]
Open the SubtitleEdit **`Settings.xml`** file in a text editor (e.g. notepad), search for **`MpcHcLocation`**, and set its value to an absolute path. For example,
```xml
<MpcHcLocation>C:\MPC-HC\mpc-hc64_nvo.exe</MpcHcLocation>
```

**Comment by Lokotito** [comment]
> 
> 
> Open the SubtitleEdit **`Settings.xml`** file in a text editor (e.g. notepad), search for **`MpcHcLocation`**, and set its value to an absolute path. For example,
> 
> ```
> <MpcHcLocation>C:\MPC-HC\mpc-hc64_nvo.exe</MpcHcLocation>
> ```
> 
> For 64-bits Windows the file name must be either `mpc-hc64_nvo.exe` or `mpc-hc64.exe`.

Works great. I was searching "mpc-hc" instead mpchc in config file. Thank you.

**Pull request closed without merging**
