### PR TITLE
Set Frame color in one more place

### PR DESCRIPTION
**Pull request by OmrSi**
When opening a file…

### CODE REVIEW

**Comment by niksedk** [comment]
What looks wrong?

**Comment by niksedk** [comment]
I love text and images in PRs :)

**Comment by OmrSi** [comment]
I agree.
I just thought you'd remember this from the previous PR.

So, when you open a file, the frame color is:
image

While it should be:
image

Which changes when you enter the textbox for the first time.

**Comment by OmrSi** [comment]
It looks inactive without that Window Frame color.

**Pull request merged**
