### PR TITLE
Work on video preview font style

### PR DESCRIPTION
**Pull request by OmrSi**
1. ASS takes `-1` for true, fixed for bold, and italic in "SsaStyle" class.
2. Used a "SsaStyle" object for MPV's preview.
3. Add hidden settings for MPV's preview and opaque box option to the UI.
4. Scale the video player's text box font size to match external video players.

### CODE REVIEW

**Comment by OmrSi** [comment]
@niksedk And notes on this?
You said you wanted to remove the Style page from the settings, what were your intentions in that regard?

**Comment by niksedk** [comment]
> 
> 
> @niksedk And notes on this?
> You said you wanted to remove the Style page from the settings, what were your intentions in that regard?

I was thinking adding "Categories" to "ASSA style manager storage. And "Default" category should not be possible to delete  - something like this:
image

And some kind of style icon in the toolbar:
image

I don't think the mpv preview font needs more settings (could have hidden settings)

**Comment by niksedk** [comment]
> 
> 
> @niksedk And notes on this?
> You said you wanted to remove the Style page from the settings, what were your intentions in that regard?
> 
> EDIT: I know you said no new features until after 3.6.0, but something should be done about MPV's font style, you made it unchangeable by the user in recent commits.

I think that's okay... but we could add hidden settings.

**Comment by OmrSi** [comment]
So I should delete the form I added and just leave the seeing in the settings file?

**Comment by niksedk** [comment]
> 
> 
> So I should delete the form I added and just leave the settings in the settings file?
Yes please :)

> 
> Also, should the icon be visible all the time or just when working with ASS?
Just for ASS

**Comment by niksedk** [comment]
Perhaps at some point a script properties icon too... like Aegisub:
image

**Comment by OmrSi** [comment]
@niksedk Removed the form.
Although I thought it's a good thing to have because sometimes you work on files that have a hardcoded subtitle and you'd want to activate the opaque box or add a vertical margin to see your translation properly.

**Comment by niksedk** [comment]
> 
> 
> @niksedk Removed the form.
> Although I thought it's a good thing to have because sometimes you work on files that have a hardcoded subtitle and you'd want to activate the opaque box or add a vertical margin to see your translation properly.

Perhaps a "opaque box" checkbox (only visible when having mpv selected) ?

**Comment by OmrSi** [comment]
@niksedk How is this?
Just the basic settings, the color, border width, and opaque option.
The border width affects the opaque box size, that's why I added it.
Let me know what you think.

I'll work on the ASSA thing in another PR.

**Comment by LeonCheung** [comment]
Whatever it goes, you guys rock. Hmm, instead of S for Style, I would suggest letter A, for ASSA for sure, after all, the idea of S was used by Aegisub, so let's be a bit more creative. :)

prmo

It uses the similar design of the N button for Netfix. Just my two cents.

**Comment by niksedk** [comment]
> 
> 
> Whatever it goes, you guys rock. Hmm, instead of S for Style, I would suggest letter A, for ASSA for sure, after all, the idea of S was used by Aegisub, so let's be a bit more creative. :)
> 
> prmo
> 
> It uses the similar design of the N button for Netfix. Just my two cents.

Looks good :)

Could you make two icons - one for "Style manager" and one for "Properties" ?
https://user-images.githubusercontent.com/1261331/105908389-700f3280-6026-11eb-8fa5-e5353c2ca968.png

My initial thought was same color and letter from Aegisub, so it will be familiar/intuitive for people who  know Aegisub, but other ideas are very welcome :)

**Comment by OmrSi** [comment]
This PR is ready to be merged, the rest of the work on Assa will be here https://github.com/SubtitleEdit/subtitleedit/pull/4763

**Comment by LeonCheung** [comment]
@niksedk, okay, here they are for discussing:
promo_v2

**Comment by niksedk** [comment]
My favorites are the red ones :)
Could you attach the images?

Could also have been "3"... (no, just kidding)

**Comment by niksedk** [comment]
@LeonCheung: As you are very talented at this, perhaps a new SE icon too? :)
The old icon looks a bit like WinXP ;)

This can be used as inspiration:
image

**Comment by OmrSi** [comment]
@niksedk I'm actually using the gray SE icon here (The one before the last). It looks cool.

**Comment by OmrSi** [comment]
Also, again, if you think no changes are needed for this PR, it's ready to be merged.

**Comment by niksedk** [comment]
> 
> 
> Also, again, if you think no changes are needed for this PR, it's ready to be merged.

I might not completely agree with the changes... but I'll look some more.

**Comment by OmrSi** [comment]
As I've said, the border width option can be removed if you think it's not necessary, but I think it is good to have the option to change the color/activate the opaque box.

That said, tell me what you think and I'll change it accordingly.

**Comment by LeonCheung** [comment]
@niksedk Hehe, glad to help. 512*512 png icons:
[icons_for_ASSA.zip](https://github.com/SubtitleEdit/subtitleedit/files/5893823/icons_for_ASSA.zip)

For a future SE Logo, I've seen there was a thread about this, many ideas gathered. Actually, I do have some ideas too, so, yes, I'll give it a try. TBC :)

**Comment by OmrSi** [comment]
@niksedk Just a reminder, I still got this.
I will add it in the other PR when I'm finished with the categories.

**Comment by OmrSi** [comment]
image

@niksedk This is what it looks like now, do you want me to only leave the opaque box option?

**Comment by OmrSi** [comment]
Okay, Nik. You drive a hard bargain. xD

image

**Pull request closed without merging**
