### PR TITLE
Add sentence continuation style

### PR DESCRIPTION
**Pull request by Flitskikker**
The past week I've been working on this feature to support different sentence continuation styles as laid out in #3417. I've been working on this for a longer time, but as a plug-in, but I got stuck wanting to do everything automatically.
This time I tried it again and kept it easier, leveraging the handy FCE dialog + preview in SE directly.

Now, after testing it with a lot of files, I believe it's finally ready for a PR.

**Settings / profiles**
Under the setting for Dialog style, there is now a setting for Continuation style per profile:

image

I've added the most common styles. Internally, there is support for further customization.
The setting has also been added to the Profile edits/exports, and default values have been set for every preset profile. It will attempt to update this when you don't have a continuation style, like with the dialog style.

Hover on the combobox for a handy preview:

image

**Fix common errors**
In FCE is where the magic happens. You will now find a new option to fix the continuation style based on the set style:

image

The "Replace ellipses at start" is hidden when you have a continuation style set, as this new option will fix that as well.

Click Next to automagically detect all needed fixes:

image

You can convert between styles, so you can add missing dots or dashes, or you can remove them.

There are a few inserts / forced narratives in the file, but they were automatically detected and unchecked. Italic or lowercase inserts and lyrics are also automatically detected and unchecked. They'll show up anyway for you to check.

You can control these detections via the new button in Settings > Tools:

image

All subtitles that end with "..." could either be interruptions or continuations. Any new beginning sentence after a "..." would be added to the dialog for you to check (unchecked by default), but that would clog up the list with a lot of unchecked-by-default items. Therefore, only new sentences after "..." that begin with a name will be displayed. Optionally, you could disable that with the last option.

**Editing features**
When splitting, continuation dots/dashes will be added accordingly:

image

When merging, continuation dots/dashes will be removed:

image

Of course, it's difficult to know if there was supposed to be a comma when replacing continuation dots/dashes. The comma will now be added based on any conjunctions at the beginning of the next sentence. These are currently hardcoded (different per language) and nowhere near complete, but it's a start.

Fun fact: The same logic is used when converting from continuation dots/dashes to none.

**Other**
Tools > Break/split long lines now pre-populates the continuation strings based on your selected style:

image

**Notes**
- I created a class ContinuationUtilities with all the stuff/helpers/utils used by this feature, but I had to add it as a subclass to the Utilities class. I tried creating a separate class, but SE wouldn't compile because of net40/netstandard21 separation. I couldn't find a way to target both versions.
- All settings and i18n have been added (also provided Dutch translations already)
- As said above, conjunctions could be added to improve the addition of commas when removing dots/dashes (per language).

---

Please test it and let me know what you think! :)

I've been getting more and more requests from people to "finish my add-dots-plugin", so I'm happy to finally have finished this (even more rich and directly in SE!). I'm sure a lot of people will find this new feature very useful.

### CODE REVIEW

**Comment by niksedk** [comment]
Looks nice :)
I've tested the `Fix common errors` (a little) and that worked perfect.

Moving `ContinuationUtilities` out as it's own class works fine here.

A little about code style... 
in SE `if statements` always uses braces, and also do check this:
https://app.codacy.com/manual/niksedk/subtitleedit/pullRequest?prid=5342644
(Codacy don't understand winforms so ignore making events static)
You should install a trial of "Resharper" (slows VS down some though).
And no `goto` statements.

Unit tests
The utilities stuff and the fix-common-errors stuff should have tests.

I'm not sure I understand the texts in the "Fix common error settings":
image
Could you make those somewhat more clear?

**Comment by niksedk** [comment]
ContinuationUtilities as separate file attached...

[ContinuationUtilities.zip](https://github.com/SubtitleEdit/subtitleedit/files/4464132/ContinuationUtilities.zip)

**Comment by niksedk** [comment]
Nice work :)

Ran a few subtitles through and the only minor thing I found is that subtitles should not use continuation styles if gap is larger than... something like 10 seconds?
image

**Comment by Flitskikker** [comment]
@niksedk 
Thank you for your feedback and advice! ReShaper is really useful, already loving it.
I spent the whole day yesterday creating tests and refining the logic, and logged off at 2 AM when the tests finally ran successfully. 😀

Will look some more into it now. It shouldn't add dots at all in the example from your screenshot.

**Comment by Flitskikker** [comment]
@niksedk 
Just pushed a new version. Added a lot of new unit tests and everything seems to work correctly now.
Also did tests with empty strings or only whitespaces ...where the whole thing crashed of course... so that has been fixed as well.
Performance took a small hit compared to the version from last night due to all the new checks, but at least it's working in all my test cases now.

Regarding your question: the default profile, "None, dots for pauses", uses a different continuation style for larger gaps (greater than max(300, minGap) ms), and only if it's a continuing sentence. For example:

```
1
00:00:01,000 --> 00:00:03,000
This is a test

2
00:00:11,000 --> 00:00:13,000
that takes long.
```

will have dots added to indicate a longer pause:

```
1
00:00:01,000 --> 00:00:03,000
This is a test...

2
00:00:11,000 --> 00:00:13,000
...that takes long.
```

**Comment by niksedk** [comment]
More good fixes :)
Yes, blank lines are always a good test :)

Found a minor issue:
image

**Comment by Flitskikker** [comment]
@niksedk 
Thank you! Added lyrics support and fixed numerous SDH bugs, together with some other fixes.
We're getting somewhere. :)

**Comment by niksedk** [comment]
It's still showing lyrics here with added dots...

**Comment by Flitskikker** [comment]
@niksedk 
Could you attach the .srt you're testing with?

**Comment by Flitskikker** [comment]
@niksedk 
Found what you were seeing. I only fixed it to add the dots _within_ the musical symbols.
I've now also added an option to ignore lyrics between musical symbols altogether:

image

**Comment by niksedk** [comment]
Could you give an explanation of the different continuation styles?
("Dots", "Dash" and "None" are pretty clear to me, but I'm not sure I get the rest 100%)

**Comment by Flitskikker** [comment]
@niksedk 
Sure.

**None**
No continuation style (commas are kept), even after long pauses.
Used in French subtitles.
```
1
00:00:01,000 --> 00:00:03,000
This is a test,

2
00:00:03,120 --> 00:00:05,120
but this is also a test

3
00:00:10,000 --> 00:00:12,000
to show how it works.
```

**None, dots for pauses (trailing only)**
No continuation style for consecutive subtitles (commas are kept).
But for pauses, trailing dots are added to indicate the pause.
Used by English Netflix: https://partnerhelp.netflixstudios.com/hc/en-us/articles/217350977-English-Timed-Text-Style-Guide (see 11.5)
```
1
00:00:01,000 --> 00:00:03,000
This is a test,

2
00:00:03,120 --> 00:00:05,120
but this is also a test...

3
00:00:10,000 --> 00:00:12,000
to show how it works.
```

**None, dots for pauses**
No continuation style for consecutive subtitles (commas are kept).
But for pauses, trailing dots _and_ leading dots are added to indicate the pause.
Used for American closed captions and Flemish subtitles.
```
1
00:00:01,000 --> 00:00:03,000
This is a test,

2
00:00:03,120 --> 00:00:05,120
but this is also a test...

3
00:00:10,000 --> 00:00:12,000
...to show how it works.
```

**Dots (trailing only)**
For each continuing sentence, trailing dots (...) are added to indicate that the sentence continues in the next subtitle, regardless of the time between subtitles.
Commas will also be replaced.
Used in Dutch professional subtitles for tv. See: https://www.auteursbond.nl/modelrichtlijnen-nederland-engelse-vertaling-002/
```
1
00:00:01,000 --> 00:00:03,000
This is a test...

2
00:00:03,120 --> 00:00:05,120
but this is also a test...

3
00:00:10,000 --> 00:00:12,000
to show how it works.
```

**Dots**
For each continuing sentence, trailing _and_ leading dots (...) are added to indicate that that the sentence is a continuation and/or that it continues in the next subtitle, regardless of the time between subtitles.
Commas will also be replaced.
Used in Dutch cinema subtitles, and by the Dutch Netflix: https://partnerhelp.netflixstudios.com/hc/en-us/articles/215350158-Dutch-Timed-Text-Style-Guide (see 5)
```
1
00:00:01,000 --> 00:00:03,000
This is a test...

2
00:00:03,120 --> 00:00:05,120
...but this is also a test...

3
00:00:10,000 --> 00:00:12,000
...to show how it works.
```

**Dash**
For each continuing sentence, a trailing _and_ leading dash is added to indicate that that the sentence is a continuation and/or that it continues in the next subtitle, regardless of the time between subtitles.
Commas will also be replaced.
Used in Scandinavian subtitles (for example Danish). See for example: https://undertekstning.dk/english/
```
1
00:00:01,000 --> 00:00:03,000
This is a test -

2
00:00:03,120 --> 00:00:05,120
- but this is also a test -

3
00:00:10,000 --> 00:00:12,000
- to show how it works.
```

**Dash, but dots for pauses**
For each continuing sentence, a trailing _and_ leading dash is added to indicate that that the sentence is a continuation and/or that it continues in the next subtitle, but when there is a pause, dots are used.
Commas will also be replaced.
Used in Scandinavian subtitles (for example Swedish).
```
1
00:00:01,000 --> 00:00:03,000
This is a test -

2
00:00:03,120 --> 00:00:05,120
- but this is also a test...

3
00:00:10,000 --> 00:00:12,000
...to show how it works.
```

Note you can hover on the Continuation style combobox to see a live example:

image

**Comment by niksedk** [comment]
These are actual pauses... could perhaps be detected by low cps (<10) and/or short sentences?
But looking at the video is probably the only 100% sure thing.

**Comment by Flitskikker** [comment]
@niksedk 
These should not be removed, because they are indeed pauses.
I'm going to look into it.

**Comment by OmrSi** [comment]
@Flitskikker Did you take into account Arabic commas when removing commas? It's `،`

**Comment by Flitskikker** [comment]
@niksedk 
Could you send me the file? I made a sample with "None, dots for pauses (trailing only)" selected, but it's not suggesting to remove the dots...

image

**Comment by Flitskikker** [comment]
@niksedk 
Ah sorry, I misread your Duration column as the Gap column.

There is only 34 ms between the two subtitles (less than a frame), so they are seen as a continuing sentence, and not as a pause.

I would say, if the subtitle already does not contain dots by default, so only for actual pauses, and you have "None" set as your profile, you would not need to enable the checkbox to 'fix' the continuation style.
You would only check the option if you'd want to convert from a subtitle with dots by default to a subtitle without dots by default.

For general purpose, I think the current way works in most cases. Full automation is never 100% possible, that's why you can verify if all changes are needed and uncheck them if needed.

Maybe, for the next version, you could change the FCE dialog into a modal, so users can double click on a line to seek to that video position, and then decide whether to check or uncheck te fix.

**Comment by niksedk** [comment]
OK, works very well - feedback might come :)
Added video player/waveform or interacting with the main window from FCE could definitively be a future improvement...

Also, that's a lot of unit tests :)

**Pull request merged**
