### PR TITLE
Update_eng_OCRFixReplaceList.xml

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by diomed** [comment]
if this deletes </OCRFixReplaceList> 
and it apparently does? it should be closed. 
Could you still add changes by yourself?

**Comment by xylographe** [comment]
Why not fix the error, and push the corrected branch? Something like,
```
git checkout patch-2
gvim Dictionaries/eng_OCRFixReplaceList.xml
git reset --soft HEAD~1
git commit -m "Updated eng_OCRFixReplaceList.xml"
git push --force origin patch-2
```

**Comment by diomed** [comment]
because I'm doing everything through browser. I don't have program.

**Comment by ivandrofly** [comment]
http://git-scm.com/downloads /cc @diomed

**Pull request closed without merging**
