### PR TITLE
Some work on list/source view

### PR DESCRIPTION
**Pull request by OmrSi**
Only update Source view when visible.
Save position in Source view on time change.
Focus shortcuts support for Source view.

Add "Go to source view" to List view's context menu.
Make a context menu for Source view and add "Go to list view" in it.

Closes https://github.com/SubtitleEdit/subtitleedit/issues/4248

### CODE REVIEW

**Comment by niksedk** [comment]
Commit cddda749c5a6cb209380ba952ae956b5255ce793 should be moved to a separate PR.
Commit 9fa0ae4b9e639c7836367befc2a4f1aa48e00648 should have the refact removed.

It would be nice to remove the tab control that contains list-/source-view... but that can be later too.

**Comment by OmrSi** [comment]
Yeah, I'm working on removing the tab control, it's why this is still a draft. :D

I've already done it, I think.
But I still need to figure out the events linked to the old tab control.
image

**Comment by niksedk** [comment]
Looks good, probably about 2 extra rows displayed now :)

To re-map events, just do it in the UI - you need to remap these:
image

**Comment by OmrSi** [comment]
@niksedk It's actually the Tab-control events that need reamping.
`TabControlSubtitleSelectedIndexChanged` and `TabControlSubtitleSelecting`.

**Comment by OmrSi** [comment]
I changed `TabControlSubtitleSelectedIndexChanged ` to `VisibleChanged` of the `splitContainerListViewAndText`,
so the one I'm thinking about is `TabControlSubtitleSelecting`.

**Comment by OmrSi** [comment]
Just to give you some context, since the tab-control is removed, now I'm working with `textBoxSource` and `splitContainerListViewAndText`.

**Comment by OmrSi** [comment]
Here goes nothing… :)

**Comment by OmrSi** [comment]
That was crazy!

**Comment by OmrSi** [comment]
@niksedk Go a chance to test it out?

**Comment by niksedk** [comment]
Yes, I've tested a while it works nicely :)

I think the list/source toggle shortcut should have a default value... perhaps F2?

**Comment by OmrSi** [comment]
> Yes, I've tested a while it works nicely :)
Great!

> I think the list/source toggle shortcut should have a default value... perhaps F2?
Yeah, seems like a good idea.

**Comment by Monovox** [comment]
Hi 
Getting rid of the tabs, will it be possible to add an optional icon in the tool bar for this list/source toggle?
Maybe it makes sense.

**Pull request merged**
