### PR TITLE
[RemoveTextFromHI] - Realign controls.

### PR DESCRIPTION
**Pull request by ivandrofly**
- [x] Auto adjust when text width is too big.
- [x] Handle batch convert width configuration

subtitleedit_2018-10-17_10-03-59

### CODE REVIEW

**Comment by niksedk** [comment]
The `Remove line if UPPERCASE` and `Remove text if contains`  are not related to `Remove text before colon`

**Comment by ivandrofly** [comment]
> The `Remove line if UPPERCASE` and `Remove text if contains` are not related to `Remove text before colon`

Okay, that can be arrange :)

**Comment by ivandrofly** [comment]
@niksedk  updated :)

image

**Comment by ivandrofly** [comment]
Is thing going in @niksedk ?

**Pull request closed without merging**
