### PR TITLE
Update ru-RU.xml

### PR DESCRIPTION
**Pull request by Elheym**
Please do not remove special characters, they are added for easier navigation.

### CODE REVIEW

**Comment by xylographe** [comment]
@niksedk Do you approve of the “special characters” in the menu items?

**Comment by niksedk** [comment]
@xylographe: It seems a bit too much to me. The "▼Ⓢ" reminds me of puzzle magazines, the "✚" seems to act like a menu item image (like some programs have). What do you think?

**Comment by aaaxx** [comment]
There's a potential problem if SE doesn't use some kind of font fallback mechanism for the interface because none of those symbols exist in Tahoma.

**Comment by xylographe** [comment]
@niksedk Last time ([`PR #1822`](https://github.com/SubtitleEdit/subtitleedit/pull/1822/files)) I removed the special-char diffs from the commit (keeping the diffs in 2d0a75aa395f77059998ec517683f552b82386c8) because IMO the “special characters” look confusing,

se-russian-with-special-characters

**Comment by Elheym** [comment]
Ok. If everything is so bad... Maybe like that will be fine? ([5a357e0](url=https://github.com/SubtitleEdit/subtitleedit/pull/1874/commits/5a357e09c5d1b2b835f708ea78dd5eb4c41e7568))

**Comment by Elheym** [comment]
No... It is too much too. It's all normal - [7b196ba](url=https://github.com/SubtitleEdit/subtitleedit/pull/1874/commits/7b196baffb327c7708b08e456a1293d9692806e9)

**Pull request closed without merging**
