### PR TITLE
[refact] - more refact for sub formats

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by niksedk** [comment]
Some of this sub formats refact is bad as SE now can detect wrong format as the "DecodeTimeCode" now ALWAYS accepts 00:00 AND 00:00:00 AND 00:00:00:00... only for some formats is this allowed!

**Comment by niksedk** [comment]
@ivandrofly: Could you look at the above issue?

**Comment by ivandrofly** [comment]
Could you give more details?
About: **00:00 AND 00:00:00 AND 00:00:00:00** 
Only subtitle which they TimeCode can be parse from Milliseconds/Frame to above time unit (e.g: hour).
There are some subtitle formats which use **00:00** to denote HH:MM (hours and minutes)

**Comment by niksedk** [comment]
Only a few formats (like Timed Text) are allowed to also use shorter variations of time codes ... allowing this for other formats will make the auto-detection of format quite a bit worse!

**Comment by ivandrofly** [comment]
Ah.... I think it's okay if we remove that generic functionality and allow only subtitle which **4 parts** timecode to get timecode from `DecodeTimeCodeFrames`.

**Comment by niksedk** [comment]
No, don't got any good ideas... sounds like a solution :)

**Comment by ivandrofly** [comment]
> sounds like a solution :)

Nice :)... I'll send PR then

**Comment by ivandrofly** [comment]
Formats and their timecode parts 
`
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
`

**Comment by ivandrofly** [comment]
Formats and their timecode parts 
`
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 31 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 35 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
FormatName: Unknown 45 - Time-Code-Parts: 2
`

**Comment by ivandrofly** [comment]
I tried to find which format really uses 3 parts time-code couldn't find 1 however I found something interesting... https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/SubtitleFormats/AvidDvd.cs#L103, should we just go for 4 or...? /cc @niksedk

**Pull request merged**
