### PR TITLE
libse: improve Matroska zlib code

### PR DESCRIPTION
**Pull request by Bond-009**
Uses System.IO.Compression instead of a 3rd party library

### CODE REVIEW

**Comment by niksedk** [comment]
Hm, it crashes... This ZLib code seems to work. Could you update the PR?

```csharp
            using (var ms = new MemoryStream())
            using (var compressed = new MemoryStream(Data))
            using (var zlib = new ZLibStream(compressed, CompressionMode.Decompress, true))
            {
                byte[] buf = new byte[short.MaxValue];
                int bufl;
                while (0 != (bufl = zlib.Read(buf, 0, buf.Length)))
                {
                    ms.Write(buf, 0, bufl);
                }

                return ms.ToArray();
            }
```

**Comment by Bond-009** [comment]
@niksedk What's the error message/stack trace?

**Comment by niksedk** [comment]
> @niksedk What's the error message/stack trace?

`````
System.InvalidOperationException
  HResult=0x80131509
  Message=Writing to the compression stream is not supported.
  Source=System.IO.Compression
  StackTrace:
   at System.IO.Compression.DeflateStream.<EnsureCompressionMode>g__ThrowCannotWriteToDeflateStreamException|44_0()
   at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Compression.DeflateStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZLibStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Nikse.SubtitleEdit.Core.ContainerFormats.Matroska.MatroskaSubtitle.GetData(MatroskaTrackInfo matroskaTrackInfo) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\libse\ContainerFormats\Matroska\MatroskaSubtitle.cs:line 39
   at Nikse.SubtitleEdit.Core.ContainerFormats.Matroska.MatroskaSubtitle.GetText(MatroskaTrackInfo matroskaTrackInfo) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\libse\ContainerFormats\Matroska\MatroskaSubtitle.cs:line 60
   at Nikse.SubtitleEdit.Core.Common.Utilities.LoadMatroskaTextSubtitle(MatroskaTrackInfo matroskaSubtitleInfo, MatroskaFile matroska, List`1 sub, Subtitle subtitle) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\libse\Common\Utilities.cs:line 2621
   at Nikse.SubtitleEdit.Forms.Main.LoadMatroskaSubtitle(MatroskaTrackInfo matroskaSubtitleInfo, MatroskaFile matroska, Boolean batchMode) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 13585
   at Nikse.SubtitleEdit.Forms.Main.ImportSubtitleFromMatroskaFile(String fileName) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 13416
   at Nikse.SubtitleEdit.Forms.Main.OpenSubtitle(String fileName, Encoding encoding, String videoFileName, String originalFileName, Boolean updateRecentFile) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 2830
   at Nikse.SubtitleEdit.Forms.Main.OpenSubtitle(String fileName, Encoding encoding, String videoFileName, String originalFileName) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 2758
   at Nikse.SubtitleEdit.Forms.Main.OpenSubtitle(String fileName, Encoding encoding) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 2747
   at Nikse.SubtitleEdit.Forms.Main.OpenNewFile() in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 2700
   at Nikse.SubtitleEdit.Forms.Main.ToolStripButtonFileOpenClick(Object sender, EventArgs e) in C:\Data\Issues\bond009\subtitleedit-zlib2\src\ui\Forms\Main.cs:line 5669
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)



![image](https://user-images.githubusercontent.com/1261331/146809467-81eb4d06-e322-4005-be5f-644fd733d3cd.png)

**Comment by niksedk** [comment]
image

**Comment by niksedk** [comment]
[srt.compressed.zip](https://github.com/SubtitleEdit/subtitleedit/files/7747059/srt.compressed.zip)

**Comment by niksedk** [comment]
Tested both scenarios - work fine :)

**Pull request merged**
