### PR TITLE
Update TextBoxSyntaxColor state on launch

### PR DESCRIPTION
**Pull request by OmrSi**
Before:

image

After:

image

### CODE REVIEW

**Comment by niksedk** [comment]
Hm, I would like to keep the button positions, to make it more clear, that they are dependent.

**Comment by OmrSi** [comment]
Makes sense, it just didn't look so when I saw it.

Do you think this is better?

image

**Comment by niksedk** [comment]
I think it's better like this:
image

**Comment by OmrSi** [comment]
Hmm, they are too far, I didn't know you meant for them to be connected when I first saw them. But, okay.

**Comment by niksedk** [comment]
> 
> 
> Hmm, they are too far, I didn't know you meant for them to be connected when I first saw them. But, okay.

Yes, they are probably a bit too far right - you can move them a little to the left...

**Comment by OmrSi** [comment]
image

**Pull request merged**
