### PR TITLE
Add "Set as default" for ASSA categories

### PR DESCRIPTION
**Pull request by OmrSi**
Closes https://github.com/SubtitleEdit/subtitleedit/issues/4818

There are bound to be a couple of bugs, but that's what testing is for. :)

### CODE REVIEW

**Comment by OmrSi** [comment]
Well, that was quick. xD

**Comment by niksedk** [comment]
Well, looks good to me :)

**Comment by LeonCheung** [comment]
Ah, so nice! Okay, here is the discussion:

1. Not sure why, I can only see the word "Set as":
screenshot1
Perhaps it's too long for UI display... Hmm, maybe some short word like "**Pin**" would also work?

2. This "**Remove**" button also needs a confirmation popup. 

3. Not sure if a "**Rename**" button is necessary, anyway. :)

**Comment by LeonCheung** [comment]
And: 
screenshot2

1. IMO the **Remove All** button should also turn gray in this case, right?
2. When trying to export an empty category, nothing happens, so it may confuse users a bit, maybe we either turn it gray, or make a message popup like "Nothing to export"?

**Comment by LeonCheung** [comment]
But another thing is, how to export multiple categories anyway? 😅

**Comment by OmrSi** [comment]
Related to this commit:
1. I think it's the font size that's causing this, looks a bit big The button might need to be bigger.

Related to categories.
2. Shouldn't be hard to add.
3. That would be up to @niksedk, what do you think is the best way to support renaming?

From the initial implementation:
4.5. Are from even before I added categories.

And import/export don't support categories yet.

**Comment by LeonCheung** [comment]
@OmrSi Cool, thanks. I think The word "Pin" would be better yet shorter as it exactly functions. Do you agree?

**Comment by LeonCheung** [comment]
@niksedk @OmrSi I know this is a closed merge, but I think it's better to discuss it further right here. :)

Just have an idea, that could be quite workable and of high expandability for something we mentioned above:

proto3

We can put things like Set as default, rename, or even re-order list... anything in the panel. 
For a default category, we can put a pin to indicate that. Oh, just found a "pin" character: 🖈   Unicode?

And, IMO we can even use "+"for "New" and "-" for "Remove".  😄  Not a big deal, just brainstorming.

**Comment by OmrSi** [comment]
@LeonCheung Yes, Nik talked about something like this and I will probably on it in the near future.
It will be a `...` button that contains the rest of the functionality.

**Comment by LeonCheung** [comment]
Cool, just made another mockup, FYI:
proto4

**Pull request merged**
