### PR TITLE
[GetDictionary] - Fix resource leak.

### PR DESCRIPTION
**Pull request by ivandrofly**
This leak is even mentioned in *coverity.com*

### CODE REVIEW

**Comment by niksedk** [comment]
Does this really fix it? I thought the object should be disposed in `Dispose`?

**Comment by ivandrofly** [comment]
yeah that is where it's disposed did you see this line => https://github.com/SubtitleEdit/subtitleedit/pull/2290/files#diff-2cea33a9c3d6f44ce30d83b540530a7fR20

**Comment by niksedk** [comment]
Could you please not edit the designer file and do it as stackoverflow suggests?
(I really would not expect custom code in the designer cs file)

**Comment by ivandrofly** [comment]
👍 ? @niksedk

**Pull request closed without merging**
