### PR TITLE
[cheetahcaption] - better lookup for latin chars

### PR DESCRIPTION
**Pull request by ivandrofly**

### CODE REVIEW

**Comment by niksedk** [comment]
I cannot make this work... does it work for you?

**Comment by ivandrofly** [comment]
> I cannot make this work... does it work for you?

I used the C# 7 dictionary initialization style... are you using VS 2017?

PS: I can change it to old-version/style

**Comment by niksedk** [comment]
Try to test it with special letters...

**Comment by ivandrofly** [comment]
updated /cc @niksedk

**Comment by niksedk** [comment]
@ivandrofly: Nice, now the code works (please always do some testing on pull requests).
Perhaps you can eliminate the duplication of the dictionary too?

**Pull request merged**
