### PR TITLE
[Internal] - Fix annoying message "FixLowercaseIToUppercaseICheckedBu…

### PR DESCRIPTION
**Pull request by ivandrofly**
…tCurrentLanguageIsNotEnglish" in FCE

Patch for: #1185 

# *Status*
- [x] Ready.
- [x] Test.

### CODE REVIEW

**Comment by ivandrofly** [comment]
Will also be removed ;) after merge `_language.FixLowercaseIToUppercaseICheckedButCurrentLanguageIsNotEnglish`

**Comment by niksedk** [comment]
Good idea - looks promising... 
Please test this well, with correct remembered checks (after restart of SE) etc...
Also, please remove commented out code and dead language tags :)

**Comment by ivandrofly** [comment]
:+1: @niksedk

**Comment by ivandrofly** [comment]
Ready /cc @niksedk

**Comment by niksedk** [comment]
Waiting for the language tags cleaning :)

**Pull request merged**
